---
# Task definition

platform: linux
container_limits: {}

# Use the 'maven:3.6.3' image from Docker Hub
image_resource:
  type: registry-image
  source:
    repository: maven
    tag: latest

# Cache the Maven repository directory
caches:
  - path: $HOME/.m2/repository

# We will provide an input called 'src' to this Task
inputs:
  - name: repo
outputs:
  - name: build

# What do we want this task to do?
# Tell Concourse the commands it should execute, in this Task
run:
  path: /bin/sh
  args:
    - -c
    - |
      mvn -f git/pom.xml test
      
      # Make this output available to the 'test' Job
      cp -R git/* build