# fly -t kaiju set-pipeline -p spring-maven -c sample-pipelines/spring-maven.yaml --team javagrunt-com
# fly -t kaiju trigger-job --job spring-maven/repo-exists --watch --team javagrunt-com

resources:
  - name: concourse-pipelines
    icon: github
    type: git
    source:
      uri: https://github.com/dashaun/concourse-pipelines
      branch: main
      git_config:
        - name: safe.directory
          value: '*'
  - name: repo
    icon: github
    type: git
    source:
      uri: https://github.com/javagrunt-com/com.javagrunt.service.cleaning
      branch: main
      git_config:
        - name: safe.directory
          value: '*'
jobs:
  - name: unit
    plan:
      - in_parallel:
        - get: repo
          version: latest # Just process the latest Git commit, not every commit (this is the default setting)
          trigger: true # Trigger this job whenever Concourse detects a new Resource version (i.e. a new Git commit)
        - get: concourse-pipelines
      - task: run-unit-tests
        file: concourse-pipelines/tasks/spring-maven-unit-test.yaml
