# fly -t kaiju set-pipeline -p spring-maven -c sample-pipelines/spring-maven.yaml --team javagrunt-com
# fly -t kaiju trigger-job --job spring-maven/repo-exists --watch --team javagrunt-com

resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/javagrunt-com/com.javagrunt.service.cleaning
      branch: main
      git_config:
        - name: safe.directory
          value: '*'
jobs:
  - name: repo-exists
    plan:
      - in_parallel:
          - get: repo
            trigger: true
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs: # add the get step as an input to this task
            - name: repo
          run: # read the file from the get step
            path: cat
            args: ["repo/README.md"]